routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PendudukController;
use App\Http\Controllers\KkController;
use App\Http\Controllers\BayiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('penduduk', PendudukController::class);
    Route::resource('kk', KkController::class);
    Route::resource('bayi', BayiController::class);

});


require __DIR__.'/auth.php';

app/Models/bayi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class bayi extends Model
{
    use HasFactory;

    protected $table = 'bayis';

    protected $fillable = ['nama_lengkap', 'nama_ayah' , 'nama_ibu' , 'tanggal_lahir', 'jenis_kelamin' ,'alamat'];
}

app/Http/Controllers/BayiController.php
<?php

namespace App\Http\Controllers;

use App\Models\bayi;
use Illuminate\Http\Request;

class BayiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bayi = Bayi::all();
        return view('bayi.index', compact('bayi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bayi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorebayiRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_lengkap'          =>  'required',
            'jenis_kelamin'         =>  'required',
            'alamat'                =>  'required',
            'nama_ayah'             =>  'required',
            'nama_ibu'              =>  'required',
            'tanggal_lahir'         =>  'required'
            
        ]);

        $bayi = new bayi;

        $bayi->nama_lengkap = $request->nama_lengkap;
        $bayi->jenis_kelamin = $request->jenis_kelamin;
        $bayi->alamat = $request->alamat;
        $bayi->nama_ayah = $request->nama_ayah;
        $bayi->tanggal_lahir = $request->tanggal_lahir;
        $bayi->nama_ibu = $request->nama_ibu;

        $bayi->save();

        return redirect()->route('bayi.index')->with('success', 'Data Berhasil Ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\bayi  $bayi
     * @return \Illuminate\Http\Response
     */
    public function show(bayi $bayi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\bayi  $bayi
     * @return \Illuminate\Http\Response
     */
    public function edit(bayi $bayi)
    {
        return view('bayi.edit', compact('bayi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatebayiRequest  $request
     * @param  \App\Models\bayi  $bayi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, bayi $bayi)
    {
        $this->validate($request, [
            'nama_lengkap'          =>  'required',
            'jenis_kelamin'         =>  'required',
            'alamat'                =>  'required',
            'nama_ayah'             =>  'required',
            'nama_ibu'              =>  'required',
            'tanggal_lahir'         =>  'required'
        ]);
    
        //get data Blog by ID
        $bayi = bayi::findOrFail($bayi->id);
        $bayi->nama_lengkap = $request->nama_lengkap;
        $bayi->jenis_kelamin = $request->jenis_kelamin;
        $bayi->alamat = $request->alamat;
        $bayi->nama_ayah = $request->nama_ayah;
        $bayi->tanggal_lahir = $request->tanggal_lahir;
        $bayi->nama_ibu = $request->nama_ibu;

        $bayi->save();

        return redirect()->route('bayi.index')->with(['success' => 'Data Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\bayi  $bayi
     * @return \Illuminate\Http\Response
     */
    public function destroy(bayi $bayi)
    {
        $bayi->delete();

        return redirect()->route('bayi.index')->with('success', 'Data Berhasil Dihapus');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/bayi/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Bayi') }}
        </h2>
    </x-slot>

    <div class="container">
        <div class="mt-5">
            @foreach($errors->all() as $error)
            <div class="alert alert-danger mt-0">
                <ul>
                    <li>{{ $error }}</li>
                </ul>
            </div>
            @endforeach
        </div>
        <div class="card mt-5">
            <div class="card-header">Tambah Data Bayi</div>
            <div class="card-body">
                <form method="post" action="{{ route('bayi.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Nama Lengkap</label>
                        <div class="col-sm-10">
                            <input type="text" name="nama_lengkap" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Jenis Kelamin</label>
                        <div class="col-sm-10">
                            <input type="text" name="jenis_kelamin" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Alamat</label>
                        <div class="col-sm-10">
                            <input type="text" name="alamat" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Nama Ayah</label>
                        <div class="col-sm-10">
                            <input type="text" name="nama_ayah" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Nama Ibu</label>
                        <div class="col-sm-10">
                            <input type="text" name="nama_ibu" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Tanggal Lahir</label>
                        <div class="col-sm-10">
                            <input type="text" name="tanggal_lahir" class="form-control" />
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" class="btn btn-outline-primary" value="Tambah Data" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/bayi/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Data Bayi') }}
        </h2>
    </x-slot>

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('bayi.update', $bayi->id) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Nama Lengkap</label>
                                <input type="text" class="form-control @error('nama_lengkap') is-invalid @enderror"
                                    name="nama_lengkap" value="{{ old('nama_lengkap', $bayi->nama_lengkap) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('nama_lengkap')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Jenis Kelamin</label>
                                <input type="text" class="form-control @error('jenis_kelamin') is-invalid @enderror"
                                    name="jenis_kelamin" value="{{ old('jenis_kelamin', $bayi->jenis_kelamin) }}"
                                    placeholder="Masukkan Jenis Kelamin">

                                <!-- error message untuk title -->
                                @error('jenis_kelamin')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Alamat</label>
                                <input type="text" class="form-control @error('alamat') is-invalid @enderror"
                                    name="alamat" value="{{ old('alamat', $bayi->alamat) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('alamat')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Nama Ayah</label>
                                <input type="text" class="form-control @error('nama_ayah') is-invalid @enderror"
                                    name="nama_ayah" value="{{ old('nama_ayah', $bayi->nama_ayah) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('nama_ayah')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Nama Ibu</label>
                                <input type="text" class="form-control @error('nama_ibu') is-invalid @enderror"
                                    name="nama_ibu" value="{{ old('nama_ibu', $bayi->nama_ibu) }}"
                                    placeholder="Masukkan Jenis Kelamin">

                                <!-- error message untuk title -->
                                @error('nama_ibu')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Tanggal Lahir</label>
                                <input type="text" class="form-control @error('tanggal_lahir') is-invalid @enderror"
                                    name="tanggal_lahir" value="{{ old('tanggal_lahir', $bayi->tanggal_lahir) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('tanggal_lahir')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="mt-3">
                                <button type="submit" class="btn btn-md btn-outline-primary">UPDATE</button>
                                <button type="reset" class="btn btn-md btn-outline-warning">RESET</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/bayi/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Data Bayi') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if($message = Session::get('success'))

            <div class="alert alert-success">
                {{ $message }}
            </div>

            @endif
            <table class="table">
                <div class="text-end">
                    <a class="btn btn-success" href="{{ route('bayi.create') }}"">Tambah Data</a>
                </div>

                <thead>
                    <p class=" text-center fw-bold fs-1 mb-3">Data Bayi</p>

                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Nama Lengkap</th>
                            <th scope="col">Jenis Kelamin</th>
                            <th scope="col">Alamat</th>
                            <th scope="col">Nama Ayah</th>
                            <th scope="col">Nama Ibu</th>
                            <th scope="col">Tanggal Lahir</th>
                            <th colspan="2" scope="col">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse ($bayi as $bayis)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $bayis->nama_lengkap }}</td>
                                <td>{{ $bayis->jenis_kelamin}}</td>
                                <td>{{ $bayis->alamat }}</td>
                                <td>{{ $bayis->nama_ayah }}</td>
                                <td>{{ $bayis->nama_ibu}}</td>
                                <td>{{ $bayis->tanggal_lahir }}</td>
                                <td class="text-center">
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                        action="{{ route('bayi.destroy', $bayis->id) }}" method="POST">
                                        <a href="{{ route('bayi.edit', $bayis->id) }}"
                                            class="btn btn-sm btn-primary">EDIT</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-outline-danger">HAPUS</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <div class="alert alert-danger">
                                Data Bayi belum Tersedia.
                            </div>
                            @endforelse
                        </tbody>
            </table>
        </div>
    </div>
</x-app-layout>