routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PendudukController;
use App\Http\Controllers\KkController;
use App\Http\Controllers\BayiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('penduduk', PendudukController::class);
    Route::resource('kk', KkController::class);
    Route::resource('bayi', BayiController::class);

});


require __DIR__.'/auth.php';

app/Models/kk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class kk extends Model
{
    use HasFactory;
    protected $table = 'kks';

    protected $fillable = ['nama_lengkap', 'jenis_kelamin' ,'alamat'];
}

app/Http/Controllers/KkController.php
<?php

namespace App\Http\Controllers;

use App\Models\kk;
use Illuminate\Http\Request;


class KkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kk = Kk::all();
        return view('kk.index', compact('kk'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorekkRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_lengkap'          =>  'required',
            'jenis_kelamin'         =>  'required',
            'alamat'                =>  'required'
            
        ]);

        $kk = new kk;

        $kk->nama_lengkap = $request->nama_lengkap;
        $kk->jenis_kelamin = $request->jenis_kelamin;
        $kk->alamat = $request->alamat;

        $kk->save();

        return redirect()->route('kk.index')->with('success', 'Data Berhasil Ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\kk  $kk
     * @return \Illuminate\Http\Response
     */
    public function show(kk $kk)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\kk  $kk
     * @return \Illuminate\Http\Response
     */
    public function edit(kk $kk)
    {
        return view('kk.edit', compact('kk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatekkRequest  $request
     * @param  \App\Models\kk  $kk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, kk $kk)
    {
        $this->validate($request, [
            'nama_lengkap'          =>  'required',
            'jenis_kelamin'         =>  'required',
            'alamat'                =>  'required'
        ]);
    
        //get data Blog by ID
        $kk = kk::findOrFail($kk->id);
        $kk->nama_lengkap = $request->nama_lengkap;
        $kk->jenis_kelamin = $request->jenis_kelamin;
        $kk->alamat = $request->alamat;

        $kk->save();

        return redirect()->route('kk.index')->with(['success' => 'Data Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\kk  $kk
     * @return \Illuminate\Http\Response
     */
    public function destroy(kk $kk)
    {
        $kk->delete();

        return redirect()->route('kk.index')->with('success', 'Data Berhasil Dihapus');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/kk/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Kepala Keluarga') }}
        </h2>
    </x-slot>

    <div class="container">
        <div class="mt-5">
            @foreach($errors->all() as $error)
            <div class="alert alert-danger mt-0">
                <ul>
                    <li>{{ $error }}</li>
                </ul>
            </div>
            @endforeach
        </div>
        <div class="card mt-5">
            <div class="card-header">Tambah Data Kepala Keluarga</div>
            <div class="card-body">
                <form method="post" action="{{ route('kk.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Nama Lengkap</label>
                        <div class="col-sm-10">
                            <input type="text" name="nama_lengkap" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Jenis Kelamin</label>
                        <div class="col-sm-10">
                            <input type="text" name="jenis_kelamin" class="form-control" />
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-label-form">Alamat</label>
                        <div class="col-sm-10">
                            <input type="text" name="alamat" class="form-control" />
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" class="btn btn-outline-primary" value="Tambah Data" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/kk/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Data Kepala Keluarga') }}
        </h2>
    </x-slot>

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('kk.update', $kk->id) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Nama Lengkap</label>
                                <input type="text" class="form-control @error('nama_lengkap') is-invalid @enderror"
                                    name="nama_lengkap" value="{{ old('nama_lengkap', $kk->nama_lengkap) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('nama_lengkap')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Jenis Kelamin</label>
                                <input type="text" class="form-control @error('jenis_kelamin') is-invalid @enderror"
                                    name="jenis_kelamin" value="{{ old('jenis_kelamin', $kk->jenis_kelamin) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('jenis_kelamin')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group pb-3">
                                <label class="font-weight-bold">Alamat</label>
                                <input type="text" class="form-control @error('alamat') is-invalid @enderror"
                                    name="alamat" value="{{ old('alamat', $kk->alamat) }}"
                                    placeholder="Masukkan Nama Lengkap">

                                <!-- error message untuk title -->
                                @error('alamat')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="mt-3">
                                <button type="submit" class="btn btn-md btn-outline-primary">UPDATE</button>
                                <button type="reset" class="btn btn-md btn-outline-warning">RESET</button>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/kk/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Kepala Keluarga') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if($message = Session::get('success'))

            <div class="alert alert-success">
                {{ $message }}
            </div>

            @endif
            <table class="table">
                <div class="text-end">
                    <a class="btn btn-success" href="{{ route('kk.create') }}"">Tambah Data</a>
                </div>

                <thead>
                    <p class=" text-center fw-bold fs-1 mb-3">Data Kepala Keluarga</p>
                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Nama Lengkap</th>
                            <th scope="col">Jenis Kelamin</th>
                            <th scope="col">Alamat</th>
                            <th colspan="2" scope="col">Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                            @php $no = 1; @endphp
                            @forelse ($kk as $kks)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $kks->nama_lengkap }}</td>
                                <td>{{ $kks->jenis_kelamin}}</td>
                                <td>{{ $kks->alamat }}</td>
                                <td class="text-center">
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                        action="{{ route('kk.destroy', $kks->id) }}" method="POST">
                                        <a href="{{ route('kk.edit', $kks->id) }}"
                                            class="btn btn-sm btn-primary">EDIT</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-outline-danger">HAPUS</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <div class="alert alert-danger">
                                Data Kepala Keluarga belum Tersedia.
                            </div>
                            @endforelse
                        </tbody>
            </table>
        </div>
    </div>
</x-app-layout>